# Generated by Django 4.0.4 on 2022-07-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoffeeMenu',
        ),
    ]
